#!/usr/bin/env bash
set -euo pipefail

usage() {
    printf 'Usage: %s [INPUT_JS] [OUTPUT_MODULE] [--ipv6]\n' "$0" >&2
    printf 'Convert a Clash Verge/Mihomo Party global JS script into an OpenClash overwrite module.\n' >&2
}

INPUT=${1:-global_script.js}
OUTPUT=${2:-openclash/lipiston-side-router}
IPV6=0
for arg in "$@"; do
    case "$arg" in
        --ipv6) IPV6=1 ;;
        -h|--help) usage; exit 0 ;;
    esac
done

if [[ ! -f "$INPUT" ]]; then
    printf 'Input file not found: %s\n' "$INPUT" >&2
    exit 1
fi

mkdir -p "$(dirname -- "$OUTPUT")"

ipv6_enable=0
ipv6_dns=0
ipv6_yaml=false
if (( IPV6 )); then
    ipv6_enable=1
    ipv6_dns=1
    ipv6_yaml=true
fi

# Read simple feature switches from the JS source. This intentionally does not execute
# arbitrary JavaScript: only literal `name: true|false` entries are consumed.
feature_enabled() {
    local feature=$1
    awk -v key="$feature" '
        $0 ~ "^[[:space:]]*" key "[[:space:]]*:[[:space:]]*(true|false)" {
            if ($0 ~ /:[[:space:]]*false([[:space:]]|,|$)/) { print 0; exit }
            print 1; exit
        }
    ' "$INPUT"
}

emit_rule_if_enabled() {
    local feature=$1
    local rule=$2
    local enabled
    enabled=$(feature_enabled "$feature" || true)
    [[ "$enabled" == 0 ]] || printf '  - %s\n' "$rule"
}

cat > "$OUTPUT" <<EOF
[General]
# Generated by openclash/convert-global-script.sh.
# Side-router mode: Fake-IP + Rule, no TUN interception.
EN_MODE = fake-ip
PROXY_MODE = rule
INTRANET_ALLOWED = 1
BYPASS_GATEWAY_COMPATIBLE = 1
ROUTER_SELF_PROXY = 1
SKIP_PROXY_ADDRESS = 1
IPV6_ENABLE = $ipv6_enable
IPV6_DNS = $ipv6_dns
DISABLE_UDP_QUIC = 1
STORE_FAKEIP = 1
ENABLE_TCP_CONCURRENT = 1
ENABLE_UNIFIED_DELAY = 1
GEODATA_LOADER = memconservative

[YAML]
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  ipv6: $ipv6_yaml
  respect-rules: true
profile:
  store-fake-ip: true
tcp-concurrent: true
unified-delay: true
geodata-loader: memconservative

proxy-groups+:
  - name: 默认节点
    type: select
    proxies: [节点选择, 自动选择, DIRECT]
  - name: 国外AI
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
  - name: YouTube
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
  - name: Spotify
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
  - name: Pixiv
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
  - name: 国外社区
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
  - name: 游戏专用
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
  - name: 苹果服务
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
  - name: 谷歌服务
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
  - name: Github
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
  - name: 微软服务
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
  - name: 跟踪分析
    type: select
    proxies: [REJECT, DIRECT, 默认节点, 节点选择, 自动选择]
  - name: 广告过滤
    type: select
    proxies: [REJECT, DIRECT, 默认节点, 节点选择, 自动选择]
  - name: 下载软件
    type: select
    proxies: [DIRECT, REJECT, 默认节点, 节点选择, 自动选择]
  - name: 国内网站
    type: select
    proxies: [DIRECT, 默认节点, 节点选择, 自动选择]
  - name: 其他外网
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]

rule-providers:
  lipiston:
    type: file
    behavior: classical
    format: yaml
    path: ./rule_provider/lipiston.yaml

+rules:
  - DOMAIN-KEYWORD,tecostudio,DIRECT
  - DOMAIN-KEYWORD,vitasub,DIRECT
  - DOMAIN-SUFFIX,mc.windmilltown.net,DIRECT
  - DOMAIN-SUFFIX,lvss.xyz,DIRECT
  - IP-CIDR,149.104.21.239/32,DIRECT,no-resolve
  - RULE-SET,lipiston,DIRECT
  - DOMAIN-SUFFIX,nrd.nie.163.com,DIRECT
  - DOMAIN-SUFFIX,webapp.163.com,DIRECT
  - DOMAIN-SUFFIX,gdl.netease.com,DIRECT
  - DOMAIN-SUFFIX,fp.ps.netease.com,DIRECT
  - DOMAIN-SUFFIX,warframe.com,DIRECT
  - DOMAIN-SUFFIX,prlrr.com,DIRECT
  - DOMAIN-SUFFIX,g5air.com,DIRECT
  - DOMAIN-SUFFIX,qslk.net,DIRECT
  - DOMAIN-SUFFIX,darensoft.com,DIRECT
  - DOMAIN-SUFFIX,gzankun.com,DIRECT
  - DOMAIN-SUFFIX,iydsj.com,DIRECT
  - DOMAIN-KEYWORD,audiences,DIRECT
  - DOMAIN-KEYWORD,rlzy,DIRECT
  - DOMAIN-KEYWORD,rsxt,DIRECT
  - DOMAIN-KEYWORD,g5air,DIRECT
  - DOMAIN-KEYWORD,lipiston,DIRECT
  - DOMAIN-KEYWORD,tailscale,DIRECT
  - DOMAIN,h1.gzankun.com,DIRECT
  - DOMAIN-SUFFIX,augmentcode.com,默认节点
  - DOMAIN-SUFFIX,javdb.com,默认节点
  - DOMAIN-SUFFIX,jdbstatic.com,默认节点
  - DOMAIN-KEYWORD,postman,默认节点
  - DOMAIN-KEYWORD,stripchat,默认节点
  - DOMAIN-KEYWORD,qbittorrent,默认节点
EOF

emit_rule_if_enabled openai 'DOMAIN-SUFFIX,openai.com,国外AI' >> "$OUTPUT"
emit_rule_if_enabled openai 'DOMAIN-SUFFIX,chatgpt.com,国外AI' >> "$OUTPUT"
emit_rule_if_enabled openai 'DOMAIN-SUFFIX,anthropic.com,国外AI' >> "$OUTPUT"
emit_rule_if_enabled youtube 'DOMAIN-SUFFIX,youtube.com,YouTube' >> "$OUTPUT"
emit_rule_if_enabled youtube 'DOMAIN-SUFFIX,googlevideo.com,YouTube' >> "$OUTPUT"
emit_rule_if_enabled spotify 'DOMAIN-SUFFIX,spotify.com,Spotify' >> "$OUTPUT"
emit_rule_if_enabled spotify 'DOMAIN-SUFFIX,scdn.co,Spotify' >> "$OUTPUT"
emit_rule_if_enabled pixiv 'DOMAIN-SUFFIX,pixiv.net,Pixiv' >> "$OUTPUT"
emit_rule_if_enabled pixiv 'DOMAIN-SUFFIX,pximg.net,Pixiv' >> "$OUTPUT"
emit_rule_if_enabled community 'DOMAIN-SUFFIX,discord.com,国外社区' >> "$OUTPUT"
emit_rule_if_enabled community 'DOMAIN-SUFFIX,facebook.com,国外社区' >> "$OUTPUT"
emit_rule_if_enabled community 'DOMAIN-SUFFIX,twitter.com,国外社区' >> "$OUTPUT"
emit_rule_if_enabled community 'DOMAIN-SUFFIX,x.com,国外社区' >> "$OUTPUT"
emit_rule_if_enabled games 'DOMAIN-SUFFIX,steamcommunity.com,游戏专用' >> "$OUTPUT"
emit_rule_if_enabled games 'DOMAIN-SUFFIX,steamstatic.com,游戏专用' >> "$OUTPUT"
emit_rule_if_enabled google 'DOMAIN-SUFFIX,google.com,谷歌服务' >> "$OUTPUT"
emit_rule_if_enabled google 'DOMAIN-SUFFIX,googleapis.com,谷歌服务' >> "$OUTPUT"
emit_rule_if_enabled github 'DOMAIN-SUFFIX,github.com,Github' >> "$OUTPUT"
emit_rule_if_enabled github 'DOMAIN-SUFFIX,githubusercontent.com,Github' >> "$OUTPUT"
emit_rule_if_enabled microsoft 'DOMAIN-SUFFIX,microsoft.com,微软服务' >> "$OUTPUT"
emit_rule_if_enabled microsoft 'DOMAIN-SUFFIX,office.com,微软服务' >> "$OUTPUT"

printf 'converted %s -> %s%s\n' "$INPUT" "$OUTPUT" "$([[ $IPV6 == 1 ]] && printf ' (IPv6 enabled)' || true)"
