#!/usr/bin/env bash
# Convert a literal Clash Verge Rev / Mihomo Party global_script.js to an OpenClash module.
# The input JavaScript is parsed as text and is never executed.
set -euo pipefail

usage() {
    printf 'Usage: %s [INPUT_JS] [OUTPUT_MODULE] [--ipv6|--no-ipv6]\n' "$0" >&2
}

INPUT=${1:-global_script.js}
OUTPUT=${2:-openclash/lipiston-side-router}
IPV6=1
for arg in "$@"; do
    case "$arg" in
        --ipv6) IPV6=1 ;;
        --no-ipv6) IPV6=0 ;;
        -h|--help) usage; exit 0 ;;
    esac
done
[[ -f "$INPUT" ]] || { printf 'Input file not found: %s\n' "$INPUT" >&2; exit 1; }
mkdir -p "$(dirname -- "$OUTPUT")"

feature_enabled() {
    local feature=$1
    awk -v key="$feature" '
        /const[[:space:]]+ruleOptions[[:space:]]*=[[:space:]]*\{/ { inside=1; next }
        inside && /^}/ { exit }
        inside && $0 ~ "^[[:space:]]*" key "[[:space:]]*:[[:space:]]*(true|false)" {
            if ($0 ~ /:[[:space:]]*false([[:space:]]|,|$)/) print 0; else print 1
            exit
        }
    ' "$INPUT" | awk 'NR==1 { print; found=1 } END { if (!found) print 1 }'
}

object_target() {
    local object=$1
    awk -v wanted="$object" '
        /const[[:space:]]+defaultCustomRules[[:space:]]*=[[:space:]]*\{/ { inside=1; next }
        inside && /^}/ { exit }
inside && index($0, wanted ": {") { object=1; next }
        object && index($0,"target:") {
            line=$0
            sub(/^[^\047]*\047/,"",line)
            sub(/\047.*$/,"",line)
            print line
            exit
        }
    ' "$INPUT"
}

# Emit kind|value|target rows for one literal array in one customRules object.
emit_array() {
    local object=$1 field=$2 kind=$3 target=$4
    awk -v wanted="$object" -v field="$field" -v kind="$kind" -v target="$target" '
        /const[[:space:]]+defaultCustomRules[[:space:]]*=[[:space:]]*\{/ { inside=1; next }
        inside && /^}/ { exit }
inside && index($0, wanted ": {") { object=1; next }
        object && /^[[:space:]]*}[,]?[[:space:]]*$/ { exit }
        object && index($0, field ": [") { in_array=1 }
        object && in_array {
            line=$0
            while (match(line, /\047[^\047]*\047/)) {
                print kind "|" substr(line,RSTART+1,RLENGTH-2) "|" target
                line=substr(line,RSTART+RLENGTH)
            }
            if (index($0, "]")) in_array=0
        }
    ' "$INPUT"
}

RULES_TMP=$(mktemp)
trap 'rm -f "$RULES_TMP"' EXIT
: > "$RULES_TMP"

# These objects are present in the source script. PROCESS-NAME is deliberately omitted:
# a router-side OpenClash instance cannot reliably match desktop process names.
for object in forceProxy microsoftSites direct defaultProxy downloadApps japanSites hkSites usSites; do
    target=$(object_target "$object" || true)
    [[ -n "$target" ]] || continue
    case "$object" in
        microsoftSites) [[ "$(feature_enabled microsoft)" == 0 ]] && continue ;;
        japanSites) [[ "$(feature_enabled japan)" == 0 ]] && continue ;;
        hkSites) [[ "$(feature_enabled hongkong)" == 0 ]] && continue ;;
        usSites) [[ "$(feature_enabled unitedstates)" == 0 ]] && continue ;;
    esac
    emit_array "$object" domainSuffix DOMAIN-SUFFIX "$target" >> "$RULES_TMP"
    emit_array "$object" domainKeyword DOMAIN-KEYWORD "$target" >> "$RULES_TMP"
    emit_array "$object" domain DOMAIN "$target" >> "$RULES_TMP"
    emit_array "$object" ipCidr IP-CIDR "$target" >> "$RULES_TMP"
    # Keep only the user's local rule provider; remote providers are not downloaded onto the router.
    emit_array "$object" ruleSets RULE-SET "$target" | awk -F'|' '$2 == "lipiston" || $2 == "ai" || $2 == "adblockmihomo"' >> "$RULES_TMP"
done

if [[ "$IPV6" == 1 ]]; then IPV6_ENABLE=1; IPV6_DNS=1; IPV6_YAML=true
else IPV6_ENABLE=0; IPV6_DNS=0; IPV6_YAML=false; fi

cat > "$OUTPUT" <<EOF
[General]
# Generated by openclash/convert-global-script-bash.sh.
# Side-router: Fake-IP + Rule; TUN is intentionally not enabled.
EN_MODE = fake-ip
PROXY_MODE = rule
INTRANET_ALLOWED = 1
BYPASS_GATEWAY_COMPATIBLE = 1
ROUTER_SELF_PROXY = 1
SKIP_PROXY_ADDRESS = 1
IPV6_ENABLE = $IPV6_ENABLE
IPV6_DNS = $IPV6_DNS
IPV6_MODE = 0
EOF
if [[ "$IPV6" == 1 ]]; then
    cat >> "$OUTPUT" <<'EOF'
ENABLE_V6_UDP_PROXY = 1
FAKEIP_RANGE6 = fdfe:dcba:9876::1/64
EOF
else
    cat >> "$OUTPUT" <<'EOF'
ENABLE_V6_UDP_PROXY = 0
EOF
fi
cat >> "$OUTPUT" <<EOF
DISABLE_UDP_QUIC = 1
STORE_FAKEIP = 1
ENABLE_TCP_CONCURRENT = 1
ENABLE_UNIFIED_DELAY = 1
GEODATA_LOADER = memconservative

[YAML]
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  ipv6: ${IPV6_YAML}
EOF
if [[ "$IPV6" == 1 ]]; then
    cat >> "$OUTPUT" <<'EOF'
  fake-ip-range6: fdfe:dcba:9876::1/64
EOF
fi
cat >> "$OUTPUT" <<'EOF'
  respect-rules: true
profile:
  store-fake-ip: true
tcp-concurrent: true
unified-delay: true
geodata-loader: memconservative

proxy-groups+:
  - name: 默认节点
    type: select
    proxies: [节点选择, 自动选择, DIRECT]
EOF

add_group() {
    cat >> "$OUTPUT" <<EOF
  - name: $2
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
EOF
}
for spec in 'openai|国外AI' 'youtube|YouTube' 'spotify|Spotify' 'pixiv|Pixiv' 'community|国外社区' 'games|游戏专用' 'apple|苹果服务' 'google|谷歌服务' 'github|Github' 'microsoft|微软服务'; do
    IFS='|' read -r option name <<< "$spec"
    [[ "$(feature_enabled "$option")" == 0 ]] || add_group "$option" "$name"
done
cat >> "$OUTPUT" <<'EOF'
  - name: 下载软件
    type: select
    proxies: [DIRECT, REJECT, 默认节点, 节点选择, 自动选择]
  - name: 国内网站
    type: select
    proxies: [DIRECT, 默认节点, 节点选择, 自动选择]
  - name: 其他外网
    type: select
    proxies: [默认节点, 节点选择, 自动选择, DIRECT]
EOF
[[ "$(feature_enabled tracker)" == 0 ]] || cat >> "$OUTPUT" <<'EOF'
  - name: 跟踪分析
    type: select
    proxies: [REJECT, DIRECT, 默认节点, 节点选择, 自动选择]
EOF
[[ "$(feature_enabled ads)" == 0 ]] || cat >> "$OUTPUT" <<'EOF'
  - name: 广告过滤
    type: select
    proxies: [REJECT, DIRECT, 默认节点, 节点选择, 自动选择]
EOF

cat >> "$OUTPUT" <<'EOF'

rule-providers:
  lipiston:
    type: file
    behavior: classical
    format: yaml
    path: ./rule_provider/lipiston.yaml

+rules:
  - DOMAIN-KEYWORD,tecostudio,DIRECT
  - DOMAIN-KEYWORD,vitasub,DIRECT
  - DOMAIN-SUFFIX,mc.windmilltown.net,DIRECT
  - DOMAIN-SUFFIX,lvss.xyz,DIRECT
  - IP-CIDR,149.104.21.239/32,DIRECT,no-resolve
  - RULE-SET,lipiston,DIRECT
  - DOMAIN-SUFFIX,nrd.nie.163.com,DIRECT
  - DOMAIN-SUFFIX,webapp.163.com,DIRECT
  - DOMAIN-SUFFIX,gdl.netease.com,DIRECT
  - DOMAIN-SUFFIX,fp.ps.netease.com,DIRECT
EOF

while IFS='|' read -r kind value target; do
    [[ -n "$kind" ]] || continue
    printf '  - %s,%s,%s\n' "$kind" "$value" "$target" >> "$OUTPUT"
done < "$RULES_TMP"

add_geosite() {
    [[ "$(feature_enabled "$1")" == 0 ]] || printf '  - GEOSITE,%s,%s\n' "$2" "$3" >> "$OUTPUT"
}
# The installed GeoSite.dat does not provide the source script's custom `ai`
# category. Keep the AI rule local so startup does not depend on that list.
if [[ "$(feature_enabled openai)" != 0 ]]; then
    printf '  - DOMAIN-SUFFIX,grazie.ai,国外AI\n' >> "$OUTPUT"
    printf '  - DOMAIN-SUFFIX,grazie.aws.intellij.net,国外AI\n' >> "$OUTPUT"
    printf '  - DOMAIN-SUFFIX,openai.com,国外AI\n' >> "$OUTPUT"
    printf '  - DOMAIN-SUFFIX,chatgpt.com,国外AI\n' >> "$OUTPUT"
    printf '  - DOMAIN-SUFFIX,anthropic.com,国外AI\n' >> "$OUTPUT"
    printf '  - DOMAIN-SUFFIX,claude.ai,国外AI\n' >> "$OUTPUT"
    printf '  - DOMAIN-SUFFIX,gemini.google.com,国外AI\n' >> "$OUTPUT"
    printf '  - DOMAIN-SUFFIX,ai.google.dev,国外AI\n' >> "$OUTPUT"
    printf '  - DOMAIN-SUFFIX,copilot.microsoft.com,国外AI\n' >> "$OUTPUT"
fi
add_geosite youtube youtube YouTube
add_geosite spotify spotify Spotify
add_geosite pixiv pixiv Pixiv
add_geosite community discord 国外社区
add_geosite community facebook 国外社区
add_geosite community twitter 国外社区
add_geosite games 'category-games@cn' 国内网站
add_geosite games steam 游戏专用
add_geosite games category-games 游戏专用
# `tracker` is not a list in the installed GeoSite.dat. Keep its strategy
# group for manual use, but do not emit an invalid rule.
# `category-ads-all` is present in GeoSite.dat but is too memory-heavy for
# this 512 MiB router when loaded together with the subscription. Keep the
# group for manual use and omit the automatic rule/provider.
add_geosite apple apple-cn 苹果服务
add_geosite google google 谷歌服务
add_geosite github github Github
add_geosite microsoft microsoft 微软服务
add_geosite microsoft 'microsoft@cn' 国内网站
add_geosite japan 'category-bank-jp' 日本网站
add_geosite hongkong 'geolocation-hk' 香港网站
add_geosite unitedstates 'geolocation-us' 美国网站
add_geosite russia 'category-ru' 俄罗斯网站

printf 'converted %s -> %s%s\n' "$INPUT" "$OUTPUT" "$([[ $IPV6 == 1 ]] && printf ' (IPv6 enabled)' || true)"
